// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearZdpLogs() {
  return window['go']['main']['App']['ClearZdpLogs']();
}

export function DeobfuscateOotbSettings() {
  return window['go']['main']['App']['DeobfuscateOotbSettings']();
}

export function DeobfuscateZdpModes() {
  return window['go']['main']['App']['DeobfuscateZdpModes']();
}

export function DisableAntiTampering() {
  return window['go']['main']['App']['DisableAntiTampering']();
}

export function EnableAntiTampering() {
  return window['go']['main']['App']['EnableAntiTampering']();
}

export function GetAllVersions() {
  return window['go']['main']['App']['GetAllVersions']();
}

export function GetAntiTamperingStatus() {
  return window['go']['main']['App']['GetAntiTamperingStatus']();
}

export function GetCurrentLogLevel() {
  return window['go']['main']['App']['GetCurrentLogLevel']();
}

export function GetDlpSdkVersion() {
  return window['go']['main']['App']['GetDlpSdkVersion']();
}

export function GetSaveMessagesLocallyStatus() {
  return window['go']['main']['App']['GetSaveMessagesLocallyStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsOotbSettingsObfuscated() {
  return window['go']['main']['App']['IsOotbSettingsObfuscated']();
}

export function IsZdpModesObfuscated() {
  return window['go']['main']['App']['IsZdpModesObfuscated']();
}

export function IsZdpServiceRunning() {
  return window['go']['main']['App']['IsZdpServiceRunning']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RegisterDev04(arg1) {
  return window['go']['main']['App']['RegisterDev04'](arg1);
}

export function RestartZdpService() {
  return window['go']['main']['App']['RestartZdpService']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function SetSaveMessagesLocally(arg1) {
  return window['go']['main']['App']['SetSaveMessagesLocally'](arg1);
}

export function StandaloneClassifier(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StandaloneClassifier'](arg1, arg2, arg3, arg4, arg5);
}

export function StartZdpService() {
  return window['go']['main']['App']['StartZdpService']();
}

export function StopZdpService() {
  return window['go']['main']['App']['StopZdpService']();
}
