// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeobfuscateOotbSettings():Promise<string>;

export function DeobfuscateZdpModes():Promise<string>;

export function DisableAntiTampering():Promise<void>;

export function EnableAntiTampering():Promise<void>;

export function GetAllVersions():Promise<main.AllVersions>;

export function GetAntiTamperingStatus():Promise<string>;

export function GetDetailsHttpCmd():Promise<string>;

export function GetDetailsHttpsCmd():Promise<string>;

export function GetDlpSdkVersion():Promise<string>;

export function GetVersion():Promise<string>;

export function IsOotbSettingsObfuscated():Promise<boolean>;

export function IsZdpModesObfuscated():Promise<boolean>;

export function IsZdpServiceRunning():Promise<boolean>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function StandaloneClassifier(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<main.ClassifierOutput>;
