// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeobfuscateOotbSettings() {
  return window['go']['main']['App']['DeobfuscateOotbSettings']();
}

export function DeobfuscateZdpModes() {
  return window['go']['main']['App']['DeobfuscateZdpModes']();
}

export function DisableAntiTampering() {
  return window['go']['main']['App']['DisableAntiTampering']();
}

export function EnableAntiTampering() {
  return window['go']['main']['App']['EnableAntiTampering']();
}

export function GetAllVersions() {
  return window['go']['main']['App']['GetAllVersions']();
}

export function GetAntiTamperingStatus() {
  return window['go']['main']['App']['GetAntiTamperingStatus']();
}

export function GetDetailsHttpCmd() {
  return window['go']['main']['App']['GetDetailsHttpCmd']();
}

export function GetDetailsHttpsCmd() {
  return window['go']['main']['App']['GetDetailsHttpsCmd']();
}

export function GetDlpSdkVersion() {
  return window['go']['main']['App']['GetDlpSdkVersion']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsOotbSettingsObfuscated() {
  return window['go']['main']['App']['IsOotbSettingsObfuscated']();
}

export function IsZdpModesObfuscated() {
  return window['go']['main']['App']['IsZdpModesObfuscated']();
}

export function IsZdpServiceRunning() {
  return window['go']['main']['App']['IsZdpServiceRunning']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StandaloneClassifier(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StandaloneClassifier'](arg1, arg2, arg3, arg4, arg5);
}
